### ISSUE TITLE
addContact does not support Custom Fields

### ISSUE THREAD

**Issue by ba66e77** [icontact/icontact-api-php#2]
The current addContact definition takes each field as a separate parameter and does not allow provide a means to add custom field values to the contact.  Converting the individual parameters to an array of extra data and adding the fields and values through a foreach should handle that problem.

**Comment by Luukyb** [comment]
Hi,
Should this be re-opened? The issue is not fixed as the change is not merged yet. 
For future reference, the change provided by @ba66e77 is here: https://github.com/icontact/icontact-api-php/pull/3
Thanks!
