### ISSUE TITLE
unsubscribing a contact from a list

### ISSUE THREAD

**Issue by mpelzsherman** [icontact/icontact-api-php#5]
Can somebody please refresh my memory as to why it is not possible to unsubscribe a contact from a list via the API, but moving a contact from one list to another IS supported? Thanks.

**Comment by aikar** [comment]
Sorry for the very ancient reply, but it is possible by changing the status:

```php
array('contactId'=>$iContactId, 'listId'=>$iListId, 'status'=>'unsubscribed');
```
