### ISSUE TITLE
getUploads function issues

### ISSUE THREAD

**Issue by SDmorgan** [icontact/icontact-api-php#8]
Issue in getUploads function.

URL should be:

return $this->makeCall("/a/{$this->setAccountId()}/c/{$this->setClientFolderId()}/uploads");

not 

return $this->makeCall("/a/{$this->setAccountId()}/c{$this->setClientFolderId()}/uploads");

Per https://www.icontact.com/developerportal/documentation/uploads

/**
	 * This method grabs the uploads associated
	 * with your iContact Account
	 * @access public
	 * @return array
	**/
	public function getUploads() {
		// Return the uploads
		return $this->makeCall("/a/{$this->setAccountId()}/c{$this->setClientFolderId()}/uploads");
	}

**Comment by aikar** [comment]
Thanks for report. Fixed!
